[profile.default]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
multiline_func_header = "attributes_first"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
