[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "22"

# Enable Next.js support
[[plugins]]
  package = "@netlify/plugin-nextjs"

